### ISSUE TITLE
No documentation on how to load a dictionary

### ISSUE THREAD

**Issue by ssbarnea** [maxb2/typer-config#254]
While trying to load a dictionary from a config file I used `Annotated[dict[str, str], typer.Option()] = {}` but I got an error as below:

```
RuntimeError: Type not yet supported: dict[str, str]
```

I searched the docs and source but only to find examples of loading strings. How an I load a dictionary?

**Comment by maxb2** [comment]
That's an issue with `typer` not `typer-config`:
https://github.com/tiangolo/typer/blob/master/typer/main.py#L788

It looks like you can't pass a dictionary as a command line argument.
For example, this is forbidden:
```bash
$ my-cli --my-param {"x": "w", "y": "z"}
RuntimeError: Type not yet supported: dict[str, str]
```

One quick workaround would be to specify the filename containing the dictionary in your config file then load the dictionary from file in the body of your command function.

Otherwise, you could create a [custom type](https://typer.tiangolo.com/tutorial/parameter-types/custom-types/) that parses the string representation into a dictionary.

Closing this as it's an upstream issue.
